genre(slipknot, heavyMetal).
start(slipknot, 1995).
play(sidWilson, dj).
play(jamesRoot, guitar).
play(craigJones, guitar).
play(craigJones, sample).
play(craigJones, keyboard).
play(shawnCrahan, percussion).
play(shawnCrahan, backingVocal).
play(mickThomson, guitar).
play(coreyTaylor, vocal).
play(alessandroVenturella, bass).
play(jayWeinberg, drums).
play(joeyJordison, drums).
play(paulGray, bass).
play(chrisFehn, percussion).
play(chrisFehn, backingVocal).
play(joshBrainard, guitar).
play(donnieSteele, guitar).
play(donnieSteele, bass).
play(andersColsefini, vocal).
play(andersColsefini, percussion).
play(gregWelts, percussion).
play(brandonDarner, percussion).
play(brandonDarner, backingVocal).
origin(joeyJordison, desMoines).
origin(slipknot, desMoines).
origin(sidWilson, desMoines).
origin(jamesRoot, lasVegas).
origin(craigJones, desMoines).
origin(shawnCrahan, desMoines).
origin(mickThomson, desMoines).
origin(coreyTaylor, desMoines).
origin(alessandroVenturella, unitedKingdom).
origin(jayWeinberg, middletown).
origin(paulGray, losAngeles).
origin(chrisFehn, desMoines).
origin(joshBrainard, lasVegas).
origin(donnieSteele, desMoines).
origin(andersColsefini, desMoines).
origin(gregWelts, desMoines).
origin(brandonDarner, desMoines).
join(sidWilson, slipknot).
join(jamesRoot, slipknot).
join(craigJones, slipknot).
join(shawnCrahan, slipknot).
join(mickThomson, slipknot).
join(coreyTaylor, slipknot).
join(alessandroVenturella, slipknot).
join(jayWeinberg, slipknot).
join(joeyJordison, slipknot).
join(paulGray, slipknot).
join(chrisFehn, slipknot).
join(joshBrainard, slipknot).
join(donnieSteele, slipknot).
join(andersColsefini, slipknot).
join(gregWelts, slipknot).
join(brandonDarner, slipknot).
whenJoin(sidWilson, 1998).
whenJoin(jamesRoot, 1999).
whenJoin(craigJones, 1996).
whenJoin(shawnCrahan, 1995).
whenJoin(mickThomson, 1996).
whenJoin(coreyTaylor, 1997).
whenJoin(alessandroVenturella, 2014).
whenJoin(jayWeinberg, 2014).
whenJoin(joeyJordison, 1995).
whenJoin(paulGray, 1995).
whenJoin(chrisFehn, 1998).
whenJoin(joshBrainard, 1995).
whenJoin(donnieSteele, 1995).
whenJoin(andersColsefini, 1995).
whenJoin(gregWelts, 1997).
whenJoin(brandonDarner, 1998).
quit(joeyJordison, slipknot).
quit(paulGray, slipknot).
quit(chrisFehn, slipknot).
quit(joshBrainard, slipknot).
quit(donnieSteele, slipknot).
quit(andersColsefini, slipknot).
quit(gregWelts, slipknot).
quit(brandonDarner, slipknot).
whenQuit(joeyJordison, 2013).
whenQuit(paulGray, 2010).
whenQuit(chrisFehn, 2019).
whenQuit(joshBrainard, 1999).
whenQuit(donnieSteele, 1996).
whenQuit(andersColsefini, 1997).
whenQuit(gregWelts, 1998).
whenQuit(brandonDarner, 1999).
album(slipknot, slipknot).
album(slipknot, iowa).
album(slipknot, subliminalVerses).
album(slipknot, live90).
album(slipknot, allHopeIsGone).
album(slipknot, antennastoHell).
album(slipknot, theGrayChapter).
whenAlbum(slipknot, 1999).
whenAlbum(iowa, 2001).
whenAlbum(subliminalVerses, 2004).
whenAlbum(live90, 2005).
whenAlbum(allHopeIsGone, 2008).
whenAlbum(antennastoHell, 2012).
whenAlbum(theGrayChapter, 2014).
concert(slipknot, london).
concert(slipknot, lisboa).
concert(slipknot, leMans).
concert(slipknot, buenosAires).
concert(slipknot, athens).
concert(slipknot, seattle).
concert(slipknot, rio).
concert(slipknot, beijing).
whenConcert(london, 2000).
whenConcert(lisboa, 2003).
whenConcert(leMans, 2004).
whenConcert(buenosAires, 2005).
whenConcert(athens, 2005).
whenConcert(seattle, 2008).
whenConcert(rio, 2011).
whenConcert(beijing, 2012).
die(paulGray, 2010).